before_script:
  # pass dependencies & selenium
  - export DEBIAN_FRONTEND=noninteractive
  - sudo apt-get -qq update
  - sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" install --no-install-recommends -y git tree gnupg shellcheck python-pip
  - sudo pip install selenium

  # Installing password-store
  - git clone https://git.zx2c4.com/password-store
  - sudo make --directory=password-store install

stages:
  - test

test:
  stage: test
  script:
    - chmod 744 tests/runtests
    - make lint
    - make test
